name: 通用扩容

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: '原始镜像 URL'
        required: true
      output_filename:
        description: '输出文件名'
        required: true
      resize_rule:
        description: '扩容规则'
        required: true

jobs:
  resize_squashfs:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils p7zip-full parted libguestfs-tools

      - name: 执行处理
        run: |
          chmod +x ./resize_disk.sh
          sudo ./resize_disk.sh "${{ github.event.inputs.image_url }}" "${{ github.event.inputs.output_filename }}" "${{ github.event.inputs.resize_rule }}"
          ls -lah

      - name: 压缩镜像
        run: |
          7z a -mx=9 "${{ github.event.inputs.output_filename }}.7z" "${{ github.event.inputs.output_filename }}"
          rm -f "${{ github.event.inputs.output_filename }}"
          ls -lah

      - name: 上传处理并压缩后的镜像
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_filename }}.7z
          path: ${{ github.event.inputs.output_filename }}.7z