name: 通用扩容

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: '原始镜像 URL'
        required: true
      expand_options:
        description: '扩容大小，例如：2G 或 500M'
        required: true
      partition_number:
        description: '要扩容的分区号 (默认: 2)'
        required: false
      output_filename:
        description: '输出文件名 (例如: expanded_image.img)'
        required: true

jobs:
  resize_squashfs:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils p7zip-full parted

      - name: 执行 SquashFS 处理
        run: |
          chmod +x ./squashfs.sh
          sudo ./squashfs.sh "${{ github.event.inputs.image_url }}" "${{ github.event.inputs.expand_options }}" "${{ github.event.inputs.output_filename }}" "${{ github.event.inputs.partition_number }}" "compress"

          ls -lah  # 列出所有文件，检查结果
          if [ ! -f "${{ github.event.inputs.output_filename }}.7z" ]; then
            echo "错误：压缩后的文件 ${{ github.event.inputs.output_filename }}.7z 未找到！"
            exit 1
          fi

      - name: 上传处理并压缩后的镜像
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_filename }}.7z
          path: ${{ github.event.inputs.output_filename }}.7z
