name: 通用扩容

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: '原始镜像 URL'
        required: true
      expand_options:
        description: '扩容大小，例如：2G 或 500M ,输入 0 仅转换格式'
        required: true
      output_filename:
        description: '输出文件名 (例如: expanded_image.img)'
        required: true
      is_efi:
        description: '镜像类型'
        required: true
        type: choice
        options:
          - '带EFI'
          - '未带EFI'

jobs:
  resize_squashfs:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils p7zip-full parted

      - name: 执行处理
        run: |
          chmod +x ./resize_disk.sh
          sudo ./resize_disk.sh "${{ github.event.inputs.image_url }}" "${{ github.event.inputs.expand_options }}" "${{ github.event.inputs.output_filename }}" "${{ github.event.inputs.is_efi }}" "compress"

          ls -lah  # 列出所有文件，检查结果
          if [ ! -f "${{ github.event.inputs.output_filename }}.7z" ]; then
            echo "错误：压缩后的文件 ${{ github.event.inputs.output_filename }}.7z 未找到！"
            exit 1
          fi

      - name: 上传处理并压缩后的镜像
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.output_filename }}.7z
          path: ${{ github.event.inputs.output_filename }}.7z
